updated prometheus scrape_interval
snappyflow/helm-charts pull request #330
Opened 2023-01-13 07:11 UTC by Pothula-Kalyani-ML

Issue: unable to get kafka broker pods heart beat and metrics in apm manger
Error:  kube-node/prom_metrics.go:198   failed to get response from endpoint {10.0.2.158 5556 metrics}, Get "[http://10.0.2.158:5556/metrics":](http://10.0.2.158:5556/metrics%22:) context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Fix : changing  evaluation_interval ,scrape_interval Scrape_timeout in Prometheus server
Before change: evaluation_interval : 5s
                         scrape_interval : 5s
                         Scrape_timeout :4s
After change: evaluation_interval : 60s
                      scrape_interval : 60s
                       Scrape_timeout :45s
Result: kafka service is being discovered and we are able to metrics in the APM Manager

2023-01-13 10:32 UTC, Thouqueer-Ahmed-ML approved these changes

2023-01-13 10:32 UTC, Thouqueer-Ahmed-ML commented
@Pothula-Kalyani-ML 
Please bump the chart version

2023-01-13 14:47 UTC, Aman-Singh-ML requested changes
Please run helm dependency update to generate new tar.gz files. Also update sf-datapath(sf-datapath/Chart,yaml) chart version. also.

2023-01-16 11:08 UTC, Aman-Singh-ML approved these changes

2023-01-17 05:33 UTC, closed without merging