Add Custom scheduler changes for all helm charts
snappyflow/helm-charts pull request #357
Opened 2023-01-25 09:52 UTC by Aman-Singh-ML

2023-01-25 10:26 UTC, Sabari-Arunkumar-ML approved these changes

2023-01-25 10:30 UTC, Thouqueer-Ahmed-ML approved these changes

2023-01-25 10:45 UTC, Nikhil-Kumar-ML approved these changes

2023-01-25 13:38 UTC, Venunadh-Veeralanka-ML requested changes
Please address the review comments.

2023-01-25 13:38 UTC, Venunadh-Veeralanka-ML commented on charts/sf-archival/Chart.yaml
> +  version: 0.1.4
why not 0.1.3?

2023-01-27 17:45 UTC, Aman-Singh-ML commented on charts/sf-datapath/sub_charts/autoscaling/sub_charts/prometheus/templates/server/deploy.yaml
>  {{- if .Values.server.schedulerName }}
change done

2023-01-27 17:45 UTC, Aman-Singh-ML commented on charts/sf-datapath/sub_charts/autoscaling/sub_charts/prometheus/templates/server/sts.yaml
>  {{- if .Values.server.schedulerName }}
change done

2023-01-27 17:45 UTC, Aman-Singh-ML commented on charts/sf-archival/Chart.yaml
> +  version: 0.1.4
change done

2023-01-30 07:46 UTC, Venunadh-Veeralanka-ML approved these changes
now changes are looking good

2023-01-30 07:47 UTC, merged