adding .Capabilities.APIVersions. condition in sf-datapath hpa and few bug fix
snappyflow/helm-charts pull request #419
Opened 2023-03-17 12:53 UTC by Poorna-BS-ML

2023-03-17 13:27 UTC, Thouqueer-Ahmed-ML requested changes

2023-03-17 13:27 UTC, Thouqueer-Ahmed-ML commented on charts/sf-datapath/sub_charts/autoscaling/templates/cp-kafka-rest-hpa.yaml
>  {{- if .Values.cpKafkaRestProxy.enabled -}}
Please move this to top of file so that single if condition will suffice
It should not be replicated

2023-03-19 14:16 UTC, Thouqueer-Ahmed-ML commented
@Poorna-BS-ML 
I am approving and merging per the test cases you mentioned to me. Please add the test cases here as well (How and Where this was tested)

2023-03-19 14:16 UTC, merged

2023-03-20 05:41 UTC, Poorna-BS-ML commented
These changes were tested on the stage set up by installing the sf-datapath chart from my fork