added system-init hook
snappyflow/helm-charts pull request #513
Opened 2023-07-19 17:48 UTC by Sonika-Prakash-ML

2023-07-20 05:20 UTC, Nikhil-Kumar-ML requested changes

2023-07-20 05:20 UTC, Nikhil-Kumar-ML commented on charts/sf-archival/templates/system-init.yaml
> +    "helm.sh/hook-weight": "-1"
change it 0 hook-weight

2023-07-20 05:47 UTC, Sonika-Prakash-ML commented on charts/sf-archival/templates/system-init.yaml
> +    "helm.sh/hook-weight": "-1"
done

2023-07-21 05:34 UTC, Nikhil-Kumar-ML approved these changes

2023-07-21 05:34 UTC, merged